# Generated by Django 5.2 on 2025-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b9_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('sporty_id', models.CharField(blank=True, max_length=50, null=True)),
                ('parser_function', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
