# Generated by Django 5.2 on 2025-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='b9_identifier',
            new_name='b9_prefix',
        ),
        migrations.AddField(
            model_name='market',
            name='b9_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
