# Generated by Django 5.2 on 2025-07-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0002_differentiate_between_prefix_and_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='ssync.market')),
            ],
        ),
    ]
