# Generated by Django 5.2 on 2025-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0003_create_outcomes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='specifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
