# Generated by Django 5.2 on 2025-08-01 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0004_add_specifier_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='MarketParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_platform', models.CharField(max_length=20)),
                ('dictionary', models.CharField(blank=True, null=True)),
                ('parser_func', models.CharField(max_length=150)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_data', to='ssync.market')),
            ],
        ),
    ]
