# Generated by Django 5.2 on 2025-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0005_created_market_parser_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketparser',
            name='from_platform',
            field=models.CharField(blank=True, choices=[('bet9ja', 'Bet9ja'), ('betking', 'BetKing'), ('sportybet', 'SportyBet'), ('nairabet', 'NairaBet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketparser',
            name='to_platform',
            field=models.CharField(choices=[('bet9ja', 'Bet9ja'), ('betking', 'BetKing'), ('sportybet', 'SportyBet'), ('nairabet', 'NairaBet')], max_length=20),
        ),
    ]
