# Generated by Django 5.2 on 2025-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0006_marketparser_from_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b9_id', models.CharField(blank=True, max_length=30, null=True)),
                ('b9_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sporty_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sporty_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b9_id', models.CharField(blank=True, max_length=50, null=True)),
                ('b9_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sporty_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sporty_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
