# Generated by Django 5.2 on 2025-08-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0007_country_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
