# Generated by Django 5.2 on 2025-08-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0008_removed_country_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='specifier',
        ),
        migrations.AddField(
            model_name='outcome',
            name='specifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
