# Generated by Django 5.2 on 2025-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0009_relocated_specifier_field_from_market_to_outcome_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('text', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='NotSupportedMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField()),
                ('market_platform', models.CharField(choices=[('bet9ja', 'Bet9ja'), ('betking', 'BetKing'), ('sportybet', 'SportyBet'), ('nairabet', 'NairaBet')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NotSupportedTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField()),
                ('market_platform', models.CharField(choices=[('bet9ja', 'Bet9ja'), ('betking', 'BetKing'), ('sportybet', 'SportyBet'), ('nairabet', 'NairaBet')], max_length=20)),
            ],
        ),
    ]
