# Generated by Django 5.2 on 2025-08-25 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0010_added_support_for_unregistered_markets_and_tourneys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='text',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='type',
            new_name='error_type',
        ),
        migrations.AddField(
            model_name='error',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
