# Generated by Django 5.2 on 2025-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0011_edited_error_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsupportedtournament',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
    ]
