# Generated by Django 5.2 on 2025-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0012_notsupportedtournament_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsupportedtournament',
            name='tourney_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
