# Generated by Django 5.2 on 2025-08-26 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0013_notsupportedtournament_tourney_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsupportedtournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
