# Generated by Django 5.2 on 2025-08-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0014_added_date_field_to_not_supported_tourney_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
    ]
