# Generated by Django 5.2 on 2025-08-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0015_added_country_field_to_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsupportedmarket',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
