# Generated by Django 5.2 on 2025-09-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssync', '0016_added_name_field_to_unsupported_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketparser',
            name='from_platform',
            field=models.CharField(blank=True, choices=[('bet9ja', 'Bet9ja'), ('sportybet', 'SportyBet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketparser',
            name='to_platform',
            field=models.CharField(choices=[('bet9ja', 'Bet9ja'), ('sportybet', 'SportyBet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notsupportedmarket',
            name='market_platform',
            field=models.CharField(choices=[('bet9ja', 'Bet9ja'), ('sportybet', 'SportyBet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notsupportedtournament',
            name='market_platform',
            field=models.CharField(choices=[('bet9ja', 'Bet9ja'), ('sportybet', 'SportyBet')], max_length=20),
        ),
    ]
